# Generated by Django 4.0.5 on 2022-07-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200)),
                ('thumb', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='thumb',
            field=models.ImageField(default='default_product.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_pdoducts',
        ),
    ]
