# Generated by Django 4.0.6 on 2022-08-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_product_thumb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
