# Generated by Django 4.0.5 on 2022-07-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_product_thumb_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_new',
            new_name='is_now',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='nickame',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='shop_products',
        ),
    ]
