# Generated by Django 4.0.5 on 2022-08-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cartitem_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_now',
            new_name='is_new',
        ),
    ]
