# Generated by Django 4.0.6 on 2022-08-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartitem'),
        ('shop', '0010_rename_adress_order_address'),
    ]

    operations = [
    ]
